### ISSUE TITLE
5주차 - 실습환경 구축하기

### ISSUE THREAD

**Issue by clghks** [JAVACAFE-STUDY/elasticsearch-2023#4]
docker에 elasticsearch 설치
* 8.10.2 버전
UI : https://github.com/javacafe-project/movie-finder

**Comment by leebokeum** [comment]
1. elasticsearch:8.10.2 설치
2. elasticsearch.yml 수정
```yml
cluster.name: "docker-cluster"
network.host: 0.0.0.0

#----------------------- BEGIN SECURITY AUTO CONFIGURATION -----------------------
#
# The following settings, TLS certificates, and keys have been automatically
# generated to configure Elasticsearch security features on 17-10-2023 12:41:10
#
# --------------------------------------------------------------------------------

# Enable security features
xpack.security.enabled: false

xpack.security.enrollment.enabled: false

# Enable encryption for HTTP API client connections, such as Kibana, Logstash, and Agents
xpack.security.http.ssl:
  enabled: false
  keystore.path: certs/http.p12

# Enable encryption and mutual authentication between cluster nodes
xpack.security.transport.ssl:
  enabled: false
  verification_mode: certificate
  keystore.path: certs/transport.p12
  truststore.path: certs/transport.p12
# Create a new cluster with the current node only
# Additional nodes can still join the cluster later
cluster.initial_master_nodes: ["9d9ae4a8858c"]

#----------------------- END SECURITY AUTO CONFIGURATION -------------------------http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: "X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization"
```
3. https://github.com/javacafe-project/movie-finder 
 - node 설치 필수
 - vue 프로젝트 실습환경 구성
